name: lint-test

on:
  push:
    branches:
      - '**'

jobs:
  lint-test:
    name: lint+test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.1", "8.2", "8.3"]
        drupal-version: ["10.2", "11.0"]
        exclude:
          - drupal-version: "11.0"
            php-version: "8.1"
          - drupal-version: "11.0"
            php-version: "8.2"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: lint+test
      run: |
        docker run \
          --env ENABLE_MODULES=turnstile_protect \
          -v $(pwd):/var/www/drupal/web/modules/contrib/turnstile_protect \
          lehighlts/drupal-ci:${DRUPAL_VERSION}-php${PHP_VERSION}
      env:
        DRUPAL_VERSION: ${{ matrix.drupal-version }}
        PHP_VERSION: ${{ matrix.php-version }}
